[package]
name = "vestazk_vault"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"
vestazk_verifier = { path = "../circuits/borrow_proof/vestazk_verifier" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-version = "2.14.0"

[dev-dependencies]
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v1.3.0" }
