[package]
name = "vesu_vault"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"

[cairo]
sierra-replace-ids = false

[dev-dependencies]
cairo_test = "2.9.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.56.0" }

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
